### ISSUE TITLE
BUG: Plugin don't work with Freeplane versions 1.11.x and later

### ISSUE THREAD

**Issue by metacoma** [metacoma/freeplane_plugin_grpc#9]
```
GRPC Freeplane::MindMapFromJSON()                                                                                     
Nov 02, 2024 1:57:04 PM org.freeplane.core.util.LogUtils severe
SEVERE: Exception in thread "grpc-default-executor-0"
java.lang.NoSuchMethodError: 'org.freeplane.features.map.NodeModel org.freeplane.features.map.MapController.newNode(ja
va.lang.Object, org.freeplane.features.map.MapModel)'                                                                 
        at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.recursiveJSONLoop(GrpcRegistration.java:366)
        at org.freeplane.plugin.grpc.GrpcRegistration$FreeplaneImpl.mindMapFromJSON(GrpcRegistration.java:441)
        at org.freeplane.plugin.grpc.FreeplaneGrpc$MethodHandlers.invoke(FreeplaneGrpc.java:1004)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:355)                       at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl
.java:867)                                                 
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)  
```
